Feature: Creating Correspondence Templates Placeholders.

  #Scenario Outline: Create SMS Placeholders
  #Given I am on CORE Admin site
  #When I want to create a "SMS corro" template
  #When I want to create a "Email corro" template for the life event "<Life Event>"
  #And I want to make the title "<Template Name>" and the description "<Template Description>"
  #And I want to make the title "<Template Name>"
  #And I give the temp the discription "<Template Description>"
  #And I make the boy text "<Template Body>"
  #Then I can save it as a "SMS" template placeholder
  #
  #Examples:
  #| Template Id | CORRO ID | Template Name                           | Template Description                                               | Template Type | Template Body                                                                           |
  #| BR-SMS1     | CRPBR118 | SMS Notify Application/Request Received | Corro Template for Notifying that Application has been received.   | SMS           | SMS Application for Birth  Certificate received.                                        |
  #| BR-SMS2     | CRPBR101 | SMS Notify Corro Sent to Email          | Corro Template for Notifying that an Email Correspondence is sent  | SMS           | SMS Regarding your bubmission a correspondence is sent to your email.VICBDM             |
  #| BR-SMS3     | CRPBR119 | SMS Notify Corro Sent via Mail          | Corro Template for Notifying that a Letter Correspondence is sent. | SMS           | SMS Regarding your bubmission a correspondence is sent to your .VICBDM                  |
  #| BR-SMS4     | CRPBR018 | SMS to Submit BRS                       | Corro Template for reminder text for BRS Submission                | SMS           | SMS Notice of Birth received. Please register birth by applying online.                 |
  #| BR-SMS5     | CRPBR019 | SMS to Submit BRS                       | Corro Template for reminder text for BRS Submission                | SMS           | SMS Notice of Birth received. Please register birth by applying online.                 |
  #| DR-SMS1     | CRPAP001 | SMS Notify Application/Request Received | Corro Template for Notifying that Application has been received.   | SMS           | SMS Application for Death Certificate received. VICBDM                                  |
  #| DR-SMS2     | CRPBR120 | SMS Notify Corro Sent to Email          | Template for Notifying that an Email Corrospondence is sent        | SMS           | SMS With regards to your submission correspondence is sent to your email address VICBDM |
  #| DR-SMS3     | CRPBR121 | SMS Notify Corro Sent via Mail          | Template for Notifying that a Letter Correspondence is sent.       | SMS           | SMS With regards to your submission correspondence is sent to your address.VICBDM       |
  
  Scenario Outline: Create Letter Placeholders
  Given I am on CORE Admin site
  When I want to create a "Letter corro" template for the life event "<Life Event>"
  And I want to make the title "<Template Name>" and the description "<Template Description>"
  And I make the boy text "<Letter Corro Body>"
  Then I can save it as a "Letter" template placeholder
  
  Examples:
  | Template Id | Template Name                                             | Template Description                                                                                                                                      | Letter Corro Body                |
  #| BR-Letter1  | Letter - BRS Part1 Recd                                   | Template for Notifying that BRS Part1 is received                                                                                                         | THe letter text body of letter1  |
  #| BR-Letter2  | Letter - Request BR Part2                                 | Template for requesting BRS Part2                                                                                                                         | THe letter text body of letter2  |
  #| BR-Letter3  | Letter - BRS Part2 Recd                                   | Template for acknowledge that BRS Part2 is received                                                                                                       | THe letter text body of letter3  |
  #| BR-Letter4  | Letter to Noify BR is Complete - No Cert                  | Template to notify that BR is compete - No Cert                                                                                                           | THe letter text body of letter4  |
  #| BR-Letter5  | Letter to Noify BR is Complete - With Cert                | Template to notify that BR is compete - Cert Ordered dispatched                                                                                           | THe letter text body of letter5  |
  #| BR-Letter6  | Letter to seek Additional Info - Birth Registration       | Template to notify that additional information is required to proceed with Birth Registration assessment                                                  | THe letter text body of letter6  |
  #| BR-Letter7  | Letter to Noify BR Certificate is Complete                | Template to notify that BR Certificate is complete                                                                                                        | THe letter text body of letter7  |
  #| BR-Letter9  | Letter to seek Additional Info - BR Certificate           | Template to notify that additional information is required to proceed with Birth Ceritifcate application assessment                                       | THe letter text body of letter8  |
  #| BR-Letter10 | Letter - Donor treatment is not held in Victoria.         | Template to advice that details of the donor treatment is not held in Victoria.                                                                           | THe letter text body of letter9  |
  #| BR-Letter11 | Letter - child name (prohibited name)                     | Template to advise that Child Name is a probihited name                                                                                                   | THe letter text body of letter10 |
  #| BR-Letter12 | Letter - Parentage dispute                                | Template to advise that Parentage dispute is indicated on BRS submission                                                                                  | THe letter text body of letter11 |
  #| BR-Letter13 | Letter - DHS for BRS                                      | Template to advise DHS to submit BRS                                                                                                                      | THe letter text body of letter12 |
  #| BR-Letter14 | Letter - BRS Part2 Not Recd                               | Template to inform that BRS Part2 is not yet received                                                                                                     | THe letter text body of letter13 |
  #| BR-Letter15 | Letter - BRS Part2 Not Recd                               | Template to inform that BR is registered without Parent2 details                                                                                          | THe letter text body of letter14 |
  #| BR-Letter16 | Letter - BR and NOB discripencies                         | Template to inform that information in BRS and NOB is not same                                                                                            | THe letter ext body of letter15  |
  #| DR-Letter4  | Letter to Noify DR is Complete - No Cert                  | Template to Correspond with the Informant provided by the Funeral Director advising the completion of registration and Death certificate  can be ordered. | THe letter text body of letter16 |
  #| DR-Letter5  | Letter to Noify DR is Complete - With Cert                | Template to Correspond with the Informant provided by the Funeral Director advising the completion of registration and Death certificate will be mailed.  | THe letter text body of letter17 |
  #| DR-Letter6  | Letter to seek Additional Info - Death Registration       | Template to notify that additional information is required to proceed with Death Registration assessment                                                  | THe letter text body of letter18 |
  #| DR-Letter7  | Letter to Noify BR Certificate is Complete                | Template to notify that DR Certificate is complete                                                                                                        | THe letter text body of letter19 |
  #| DR-Letter8  | Letter to seek Additional Info - DR Certificate           | Template to notify that additional information is required to proceed with Death  Certificate application assessment                                      | THe letter text body of letter20 |
  #| DR-Letter9  | Letter Request to FD for DRS submission                   | Template to request FD to submit DRS                                                                                                                      | THe letter text body of letter21 |
  #| DR-Letter10 | Letter Request for MP for MCCD submission                 | Template to request Doctor to submit COD                                                                                                                  | THe letter text body of letter22 |
  #| DR-Letter11 | Letter Request for DRS submission                         | Template to request Family Members to submit DRS                                                                                                          | THe letter text body of letter23 |
  #| DR-Letter12 | Letter Request for DRS submission                         | Template to request FD to submit DRS                                                                                                                      | THe letter text body of letter24 |
  #| DR-Letter13 | Letter Request for Medical Practioner for MCCD submission | Template to request Doctor to submit COD                                                                                                                  | THe letter text body of letter25 |
  #| DR-Letter14 | Letter to Medical Practioner - Eligibility                | Template to request Doctor to submit COD                                                                                                                  | THe letter text body of letter26 |
  #| DR-Letter15 | Letter - COD and NOB discripencies                        | Template to Corrospond with Doctor (MCCPD) and Hospital (NOB) to advise that information on MCCPD inconsistent with NOB or BR or BRS                      | THe letter text body of letter27 |
  #
  Scenario Outline: Create Email Placeholders
    Given I am on CORE Admin site
    When I want to create a "Email corro" template for the life event "<Life Event>"
    And I want to make the title "<Template Name>" and the description "<Template Description>"
    And I want the email to have a the related SMS "<Related SMS>" and the Signature Block to be "<signature block>"
    And I want to make the email subject "<email Subject>"
    And I make the boy text "<Email Corro Body>"
    Then I can save it as a "Email" template placeholder

    Examples: 
      | Template Name                                      | Template Description                                                                                                      | Life Event | Related SMS | Email Corro Body                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | email Subject                                                   | signature block                           |
      | Email - BRS Part1 Recd                             | Template for Notifying that BRS Part 1 is received                                                                        | Birth      | CRPAP02     | DumyOne                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | This is the subject of email                                    | This is the body of the email to be senty |
      | Email - BRS Part1 Recd                             | Corro Template for Notifying that BRS Part 1 is received                                                                  | Birth      | CRPAP02     | Dear  Title   Surname  I refer to the lodgement of the birth registration statement with the Victorian Registry of Births. Deaths and Marriages (the Registry).  Insert additional text for Email Content here…..  Please include the above reference number with any correspondence sent to the Registry. If you would like more information please visit the Registry’s website www.bdm.vic.gov.au or if you need to discuss this matter. contact on 03 XXXX XXXX and quote the above reference number.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | Registration of Birth - BRS Part 1 Received                     | BR-EmailSignature.doc                     |
      | Email - Request BR Part 2                          | Corro Template for requesting BRS Part 2                                                                                  | Birth      | CRPAP02     | Dear  $$Parent2 $$Last Name  I refer to the lodgement of the birth registration statement (Part 1) with the Victorian Registry of Births Deaths and Marriages (the Registry). I refer to the lodgement of the Birth Registration Statement (Part 1) with the Victorian Registry of Births Deaths and Marriages (the Registry). Part 2 submission is required for Parent 2. Please visit following link  link  to provide details for BRS Part2. You will be required to register for an online user account before filling detail for part 2. If you already have an online user account you can use the same to log in and complete Part 2.  Insert additional text as required …..  Please arrange to complete Part 2 within xx days of this email to enable the registration to proceed. If no response is received the registration will be delayed. If you would like more information please visit the Registry’s website www.bdm.vic.gov.au or if you need to discuss this matter contact on 03 XXXXXXX and quote the above reference number. | Registration of Birth - BRS Part 2 required                     | BR-EmailSignature.doc                     |
      | Email - BRS Part2 Recd                             | Corro Template for acknowledge that BRS Part 2 is received                                                                | Birth      | CRPAP02     | Dear  informant2 LastName  I refer to the lodgement of the birth registration statement with the Victorian Registry of Births Deaths and Marriages (the Registry).  Insert additional text as required  Please include the above reference number with any correspondence sent to the Registry. If you would like more information please visit the Registry’s website www.bdm.vic.gov.au or if you need to discuss this matter contact on 03 XXXX XXXX and quote the above reference number.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | Registration of Birth - BRS Part 2 Received                     | BR-EmailSignature.doc                     |
      | Email to Notify BR is Complete - No Cert           | Corro Template to notify that BR is compete - No Cert                                                                     | Birth      | CRPAP02     | Dear  Title   Surname  I refer to the lodgement of the birth registration statement with the Victorian Registry of Births Deaths and Marriages (the Registry).  Insert text for Email Content …..  • Additional text; and • Additional text; and • Additional text; and • Additional text; and Please arrange to respond to the Registry within 28 days of this email to enable the registration to proceed. If no response is received the registration will be delayed and no certificate will be available.This confirmation can be emailed to bdmbirths@justice.vic.gov.au or posted to: Births Deaths and Marriages GPO Box 5220 MELBOURNE  VIC  3001 Please include the above reference number with any correspondence sent to the Registry. If you would like more information please visit the Registry’s website www.bdm.vic.gov.au or if you need to discuss this matter contact  Officer Name  on 03 9613  Last 4 Digits  and quote the above reference number.                                                                           | Registration of Birth - Completed                               | BR-EmailSignature.doc                     |
      | Email to Notify BR is Complete - With Cert         | Corro Template to notify that BR is compete - Cert Ordered dispatched                                                     | Birth      | CRPAP02     | Dear  Title   Surname  I refer to the lodgement of the birth registration statement with the Victorian Registry of Births Deaths and Marriages (the Registry).  Insert text for Email Content …..  • Additional text; and • Additional text; and • Additional text; and • Additional text; and Please arrange to respond to the Registry within 28 days of this email to enable the registration to proceed. If no response is received the registration will be delayed and no certificate will be available.This confirmation can be emailed to bdmbirths@justice.vic.gov.au or posted to: Births Deaths and Marriages GPO Box 5220 MELBOURNE  VIC  3001 Please include the above reference number with any correspondence sent to the Registry. If you would like more information please visit the Registry’s website www.bdm.vic.gov.au or if you need to discuss this matter contact  Officer Name  on 03 9613  Last 4 Digits  and quote the above reference number.                                                                           | Registration of Birth - Completed                               | BR-EmailSignature.doc                     |
      | Email to seek Additional Info - Birth Registration | Corro Template to notify that additional information is required to proceed with Birth Registration assessment            | Birth      | CRPAP02     | Dear  Title   Surname  I refer to the lodgement of the birth registration statement with the Victorian Registry of Births Deaths and Marriages (the Registry).  Insert text for Email Content …..  • Additional text; and • Additional text; and • Additional text; and • Additional text; and Please arrange to respond to the Registry within 28 days of this email to enable the registration to proceed. If no response is received the registration will be delayed and no certificate will be available.This confirmation can be emailed to bdmbirths@justice.vic.gov.au or posted to: Births Deaths and Marriages GPO Box 5220 MELBOURNE  VIC  3001 Please include the above reference number with any correspondence sent to the Registry. If you would like more information please visit the Registry’s website www.bdm.vic.gov.au or if you need to discuss this matter contact  Officer Name  on 03 9613  Last 4 Digits  and quote the above reference number.                                                                           | Registration of Birth - Additional Information required         | BR-EmailSignature.doc                     |
      | Email to Noify BR Certificate is Complete          | Corro Template to notify that BR Certificate is compete                                                                   | Birth      | CRPAP02     | Dear  Title   Surname  I refer to the lodgement of the birth registration statement with the Victorian Registry of Births Deaths and Marriages (the Registry).  Insert text for Email Content …..  • Additional text; and • Additional text; and • Additional text; and • Additional text; and Please arrange to respond to the Registry within 28 days of this email to enable the registration to proceed. If no response is received the registration will be delayed and no certificate will be available.This confirmation can be emailed to bdmbirths@justice.vic.gov.au or posted to: Births Deaths and Marriages GPO Box 5220 MELBOURNE  VIC  3001 Please include the above reference number with any correspondence sent to the Registry. If you would like more information please visit the Registry’s website www.bdm.vic.gov.au or if you need to discuss this matter contact  Officer Name  on 03 9613  Last 4 Digits  and quote the above reference number.                                                                           | Birth Certificate Application - Completed                       | BR-EmailSignature.doc                     |
      | Email to seek Additional Info - BR Certificate     | Corro Template to notify that additional information is required to proceed with Birth Certificate application assessment | Birth      | CRPAP02     | Dear  Title   Surname  I refer to the lodgement of the birth registration statement with the Victorian Registry of Births Deaths and Marriages (the Registry).  Insert text for Email Content …..  • Additional text; and • Additional text; and • Additional text; and • Additional text; and Please arrange to respond to the Registry within 28 days of this email to enable the registration to proceed. If no response is received the registration will be delayed and no certificate will be available. This confirmation can be emailed to bdmbirths@justice.vic.gov.au or posted to:Births Deaths and Marriages GPO Box 5220 MELBOURNE  VIC  3001 Please include the above reference number with any correspondence sent to the Registry. If you would like more information please visit the Registry’s website www.bdm.vic.gov.au or if you need to discuss this matter contact  Officer Name  on 03 9613  Last 4 Digits  and quote the above reference number.                                                                           | Birth Certificate Application - Additional Information required | BR-EmailSignature.doc                     |
      | Email - Donor treatment is not held in Victoria.   | Corro Template to advise that details of the donor treatment is not held in Victoria.                                     | Birth      | CRPAP02     | Dear  Title   Surname  I refer to the lodgement of the birth registration statement with the Victorian Registry of Births Deaths and Marriages (the Registry).  Insert text for Email Content …..  • Additional text; and • Additional text; and • Additional text; and • Additional text; and Please arrange to respond to the Registry within 28 days of this email to enable the registration to proceed. If no response is received the registration will be delayed and no certificate will be available. This confirmation can be emailed to bdmbirths@justice.vic.gov.au or posted to: Births Deaths and Marriages GPO Box 5220 MELBOURNE  VIC  3001 Please include the above reference number with any correspondence sent to the Registry. If you would like more information please visit the Registry’s website www.bdm.vic.gov.au or if you need to discuss this matter contact  Officer Name  on 03 9613  Last 4 Digits  and quote the above reference number.                                                                          | Registration of Birth - Donor details                           | BR-EmailSignature.doc                     |
      | Email - child name (prohibited name)               | Corro Template to advise that Child Name is a prohibited name                                                             | Birth      | CRPAP02     | Dear  Title   Surname  I refer to the lodgement of the birth registration statement with the Victorian Registry of Births Deaths and Marriages (the Registry).  Insert text for Email Content …..  • Additional text; and • Additional text; and • Additional text; and • Additional text; and Please arrange to respond to the Registry within 28 days of this email to enable the registration to proceed. If no response is received the registration will be delayed and no certificate will be available. This confirmation can be emailed to bdmbirths@justice.vic.gov.au or posted to: Births Deaths and Marriages GPO Box 5220 MELBOURNE  VIC  3001 Please include the above reference number with any correspondence sent to the Registry. If you would like more information please visit the Registry’s website www.bdm.vic.gov.au or if you need to discuss this matter contact  Officer Name  on 03 9613  Last 4 Digits  and quote the above reference number.                                                                          | Registration of Birth - prohibited name                         | BR-EmailSignature.doc                     |
      | Email -  Parentage dispute                         | Corro Template to advise that Parentage dispute is indicated on BRS submission                                            | Birth      | CRPAP02     | Dear  Title   Surname  I refer to the lodgement of the birth registration statement with the Victorian Registry of Births Deaths and Marriages (the Registry).  Insert text for Email Content …..  • Additional text; and • Additional text; and • Additional text; and • Additional text; and Please arrange to respond to the Registry within 28 days of this email to enable the registration to proceed. If no response is received the registration will be delayed and no certificate will be available. This confirmation can be emailed to bdmbirths@justice.vic.gov.au or posted to: Births Deaths and Marriages GPO Box 5220 MELBOURNE  VIC  3001 Please include the above reference number with any correspondence sent to the Registry. If you would like more information please visit the Registry’s website www.bdm.vic.gov.au or if you need to discuss this matter contact  Officer Name  on 03 9613  Last 4 Digits  and quote the above reference number.                                                                          | Registration of Birth - Parentage Dispute                       | BR-EmailSignature.doc                     |
      | Email - DHS for BRS                                | Corro Template to advise DHS to submit BRS                                                                                | Birth      | CRPAP02     | Dear  Title   Surname  I refer to the lodgement of the birth registration statement with the Victorian Registry of Births Deaths and Marriages (the Registry).  Insert text for Email Content …..  • Additional text; and • Additional text; and • Additional text; and • Additional text; and Please arrange to respond to the Registry within 28 days of this email to enable the registration to proceed. If no response is received the registration will be delayed and no certificate will be available. This confirmation can be emailed to bdmbirths@justice.vic.gov.au or posted to: Births Deaths and Marriages GPO Box 5220 MELBOURNE  VIC  3001 Please include the above reference number with any correspondence sent to the Registry. If you would like more information please visit the Registry’s website www.bdm.vic.gov.au or if you need to discuss this matter contact  Officer Name  on 03 9613  Last 4 Digits  and quote the above reference number.                                                                          | Registration of Birth - DHS request                             | BR-EmailSignature.doc                     |
      | Email - BRS Part2 Not Recd                         | Corro Template to inform that BRS Part 2 is not yet received                                                              | Birth      | CRPAP02     | Dear  Title   Surname  I refer to the lodgement of the birth registration statement with the Victorian Registry of Births Deaths and Marriages (the Registry).  Insert text for Email Content …..  • Additional text; and • Additional text; and • Additional text; and • Additional text; and Please arrange to respond to the Registry within 28 days of this email to enable the registration to proceed. If no response is received the registration will be delayed and no certificate will be available. This confirmation can be emailed to bdmbirths@justice.vic.gov.au or posted to: Births Deaths and Marriages GPO Box 5220 MELBOURNE  VIC  3001 Please include the above reference number with any correspondence sent to the Registry. If you would like more information please visit the Registry’s website www.bdm.vic.gov.au or if you need to discuss this matter contact  Officer Name  on 03 9613  Last 4 Digits  and quote the above reference number.                                                                          | Registration of Birth - Awaiting BRS Part 2                     | BR-EmailSignature.doc                     |
      | Email - BR Registered                              | Corro Template to inform that BR is registered without Parent 2 details                                                   | Birth      | CRPAP02     | Dear  Title   Surname  I refer to the lodgement of the birth registration statement with the Victorian Registry of Births Deaths and Marriages (the Registry).  Insert text for Email Content …..  • Additional text; and • Additional text; and • Additional text; and • Additional text; and Please arrange to respond to the Registry within 28 days of this email to enable the registration to proceed. If no response is received the registration will be delayed and no certificate will be available. This confirmation can be emailed to bdmbirths@justice.vic.gov.au or posted to: Births Deaths and Marriages GPO Box 5220 MELBOURNE  VIC  3001 Please include the above reference number with any correspondence sent to the Registry. If you would like more information please visit the Registry’s website www.bdm.vic.gov.au or if you need to discuss this matter contact  Officer Name  on 03 9613  Last 4 Digits  and quote the above reference number.                                                                          | Registration of Birth - BR completed without Parent 2           | BR-EmailSignature.doc                     |
      | Email - BR and NOB discrepancies                   | Corro Template to inform that information in BRS and NOB is not same                                                      | Birth      | CRPAP02     | Dear  Title   Surname  I refer to the lodgement of the birth registration statement with the Victorian Registry of Births Deaths and Marriages (the Registry).  Insert text for Email Content …..  • Additional text; and • Additional text; and • Additional text; and • Additional text; and Please arrange to respond to the Registry within 28 days of this email to enable the registration to proceed. If no response is received the registration will be delayed and no certificate will be available. This confirmation can be emailed to bdmbirths@justice.vic.gov.au or posted to: Births Deaths and Marriages GPO Box 5220 MELBOURNE  VIC  3001 Please include the above reference number with any correspondence sent to the Registry. If you would like more information please visit the Registry’s website www.bdm.vic.gov.au or if you need to discuss this matter contact  Officer Name  on 03 9613  Last 4 Digits  and quote the above reference number.                                                                          | Registration of Birth - Information not complete                | BR-EmailSignature.doc                     |
