Feature: Creating Correspondence Templates Placeholders for Emails.

  Scenario Outline: Create Email Placeholders
    Given I am on CORE Admin site
    When I want to create a "Email corro" template
    And I want to make the title "<Template Name>" and the description "<Template Description>" and the "<Life Event>" and the "<Document Type>"
    And I want the email to have a the related SMS "<Related SMS Template>" and the Signature Block to be "<Signature block>"
    And I want to make the email subject "<Email Subject>"
    Then I can save the template placeholder

    Examples: 
      | Template Name | Template Description                                                                                           | Life Event | Document Type | Related SMS Template | Email Subject                                           | Signature block   |
      | Template Name | Template Description                                                                                           | Life Event | Document Type | Related SMS Template | Email Subject                                           | Signature block   |
      | BR-Email1     | Corro Template for Notifying that BRS Part 1 is received                                                       |            |               | GR-SMS1              | Registration of Birth - BRS Part 1 Received             | BR-EmailSignature |
      | BR-Email2     | Corro Template for requesting BRS Part 2                                                                       |            |               | GR-SMS1              | Registration of Birth - BRS Part 2 required             | BR-EmailSignature |
      | BR-Email2A    | Corro Template for resend for requesting BRS Part 2                                                            |            |               | GR-SMS1              | Registration of Birth - BRS Part 2 required             | BR-EmailSignature |
      | BR-Email3     | Corro Template for acknowledge that BRS Part 2 is received                                                     |            |               | GR-SMS1              | Registration of Birth - BRS Part 2 Received             | BR-EmailSignature |
      | BR-Email4     | Corro Template to notify that BR is compete - No Cert                                                          |            |               | GR-SMS1              | Registration of Birth - Completed                       | BR-EmailSignature |
      | BR-Email5     | Corro Template to notify that BR is compete - Cert Ordered dispatched                                          |            |               | GR-SMS1              | Registration of Birth - Completed                       | BR-EmailSignature |
      | BR-Email6     | Corro Template to notify that additional information is required to proceed with Birth Registration assessment | Births     | BRS           | GR-SMS1              | Registration of Birth - Additional Information required | BR-EmailSignature |
      | BR-Email9     | Corro Template to advise that details of the donor treatment is not held in Victoria.                          | Births     | BRS           | GR-SMS1              | Registration of Birth - Donor details                   | BR-EmailSignature |
      | BR-Email10    | Corro Template to advise that Child Name is a prohibited name                                                  | Births     | BRS           | GR-SMS1              | Registration of Birth - prohibited name                 | BR-EmailSignature |
      | BR-Email11    | Corro Template to advise that Parentage dispute is indicated on BRS submission                                 | Births     | BRS           | GR-SMS1              | Registration of Birth - Parentage Dispute               | BR-EmailSignature |

      
      #| BR-Letter1    | Corro Template for Notifying that BRS Part 1 is received | Births    | BRS           | BR-LetterBranding |
      #| BR-Letter2    | Corro Template for requesting BRS Part 2                 | Births    | BRS           | BR-LetterBranding |
      #| BR-Letter3               | Corro Template for acknowledge that BRS Part 2 is received                                                                                                  | Births             | BRS                    | BR-LetterBranding    |
      #| BR-Letter4               | Corro Template to notify that BR is compete - No Cert                                                                                                       | Births             | BRS                    | BR-LetterBranding    |
      #| BR-Letter5               | Corro Template to notify that BR is compete - Cert Ordered dispatched                                                                                       | Births             | BRS                    | BR-LetterBranding    |
      #| BR-Letter6               | Corro Template to notify that additional information is required to proceed with Birth Registration assessment                                              | Births             | BRS                    | BR-LetterBranding    |
      #| BR-Letter9               | Corro Template to advice that details of the donor treatment is not held in Victoria.                                                                       | Births             | BRS                    | BR-LetterBranding    |
      #| BR-Letter10              | Corro Template to advise that Child Name is a prohibited name                                                                                               | Births             | BRS                    | BR-LetterBranding    |
      #| BR-Letter11              | Corro Template to advise that Parentage dispute is indicated on BRS submission                                                                              | Births             | BRS                    | BR-LetterBranding    |
      #| BR-Letter12              | Corro Template to advise DHS to submit BRS                                                                                                                  | Births             | BRS                    | BR-LetterBranding    |
      #| BR-Letter13              | Corro Template to inform that BRS Part 2 is not yet received                                                                                                | Births             | BRS                    | BR-LetterBranding    |
      #| BR-Letter14              | Corro Template to inform that BR is registered without Parent 2 details                                                                                     | Births             | BRS                    | BR-LetterBranding    |
      #| BR-Letter15              | Corro Template to inform that information in BRS and NOB is not same                                                                                        | Births             | BRS                    | BR-LetterBranding    |
      #| BR-Letter16              | Corro Template to notify adoptive parents that BR is compete - No Cert                                                                                      | Adoption           | Adoption Notification  | BR-LetterBranding    |
      #| BR-Letter17              | Corro Template to notify commissioning parents to submit BRS                                                                                                | Surrogacy          | Surrogacy Notification | BR-LetterBranding    |
      #| BR-Letter18              | Corro Template to notify adoptive parents that BR is compete - No Cert                                                                                      | Adoption           | Adoption Notification  | BR-LetterBranding    |
      #| BR-Letter19              | Corro Template to notify adoptive parents that BR is compete - No Cert                                                                                      | Adoption           | Adoption Notification  | BR-LetterBranding    |
      #| DR-Letter1               | Template to Correspond with the 'Informant' provided by the Funeral Director advising the completion of registration and Death certificate  can be ordered. | Deaths             | DRS                    | DR-LetterBranding    |
      #| DR-Letter2               | Template to Correspond with the 'Informant' provided by the Funeral Director advising the completion of registration and Death certificate will be mailed.  | Deaths             | DRS                    | DR-LetterBranding    |
      #| DR-Letter3               | Template to notify that additional information is required to proceed with Death Registration assessment                                                    | Deaths             | DRS                    | DR-LetterBranding    |
      #| DR-Letter6               | Template to request FD to submit DRS                                                                                                                        | Deaths             | COD                    | DR-LetterBranding    |
      #| DR-Letter7               | Template to request Doctor to submit COD                                                                                                                    | Deaths             | DRS                    | DR-LetterBranding    |
      #| DR-Letter8               | Template to request Family Members to submit DRS                                                                                                            | Deaths             | COD                    | DR-LetterBranding    |
      #| DR-Letter9               | Template to request Doctor to submit COD                                                                                                                    | Deaths             | DRS                    | DR-LetterBranding    |
      #| DR-Letter10              | Template to Corrospond with Doctor (MCCPD) and Hospital (NOB) to advise that information on MCCPD inconsistent with NOB or BR or BRS                        | Births             | BRS                    | DR-LetterBranding    |
      #| RR-Letter1               | Corro Template for Notifying hat Relationship Applicant 1 submission is received                                                                            | Relationship       | RLR Notification       | RR-LetterBranding    |
      #| RR-Letter2               | Corro Template for requesting Relationship Part 2                                                                                                           | Relationship       | RLR Notification       | RR-LetterBranding    |
      #| RR-Letter3               | Corro Template for acknowledge that Applicant 2 submission is received                                                                                      | Relationship       | RLR Notification       | RR-LetterBranding    |
      #| RR-Letter4               | Corro Template to Notify that Cooling off period has started                                                                                                | Relationship       | RLR Notification       | RR-LetterBranding    |
      #| RR-Letter18   | Corr Template to Notify  to notify that additional information is required to proceed with Relationship Registration        | Relationship   | RLR Notification | RR-LetterBranding  |
      #| RR-Letter5    | Corr Template to Notify that additional documentation / information is not received and therefore the application is closed | Relationship   | RLR Notification | RR-LetterBranding  |
      #| RR-Letter6    | Corr Template to acknowledge that a witdrawal request for the relationship application has been received and processed      | Relationship   | RLR Notification | RR-LetterBranding  |
      #| RR-Letter7    | Corr Template to acknowledge that a witdrawal request for the relationship application has been received and processed      | Relationship   | RLR Notification | RR-LetterBranding  |
      #| RR-Letter8    | Corro Template to notify that RR is compete - No Cert                                                                       | Relationship   | RLR Notification | RR-LetterBranding  |
      #| RR-Letter9    | Corro Template to notify that RR is compete - Cert Ordered dispatched                                                       | Relationship   | RLR Notification | RR-LetterBranding  |
      #| RR-Letter10   | Corro Template for Notifying that Relationship Revocation Applicant 1 submission is received                                | Relationship   | RLR Notification | RR-LetterBranding  |
      #| RR-Letter11   | Corro Template for requesting Revocation Part 2                                                                             | Relationship   | RLR Notification | RR-LetterBranding  |
      #| RR-Letter12   | Corro Template for acknowledge that Applicant 2 submission of revocation is received                                        | Relationship   | RLR Notification | RR-LetterBranding  |
      #| RR-Letter13   | Corr Template to acknowledge that a witdrawal request for the relationship revocation has been received and processed       | Relationship   | RLR Notification | RR-LetterBranding  |
      #| RR-Letter14   | Corr Template to acknowledge that a witdrawal request for the relationship revocation has been received and processed       | Relationship   | RLR Notification | RR-LetterBranding  |
      #| RR-Letter15   | Corro Template to notify that revocation  is compete - No Cert                                                              | Relationship   | RLR Notification | RR-LetterBranding  |
      #| RR-Letter16   | Corro Template to Notify that Cooling off period has started                                                                | Relationship   | RLR Notification | RR-LetterBranding  |
      #| CON-Letter1   | Corro Template for Notifying that CON application for Vic Born Adult is received                                            | Change of Name | CON Notification | CON-LetterBranding |
      #| CON-Letter2   | Corro Template for Notifying that CON application for non-Vic Born  Adult is received                                       | Change of Name | CON Notification | CON-LetterBranding |
      #| CON-Letter3   | Corro Template for requesting CON Part 2                                                                                    | Change of Name | CON Notification | CON-LetterBranding |
      #| CON-Letter4   | Corro Template for requesting CON Part 2                                                                                    | Change of Name | CON Notification | CON-LetterBranding |
      #| CON-Letter5   | Corro Template to notify that additional information is required to proceed with Registration assessment                    | Change of Name | CON Notification | CON-LetterBranding |
      #| CON-Letter6   | Corro Template to notify that CON is compete - No Cert                                                                      | Change of Name | CON Notification | CON-LetterBranding |
      #| CON-Letter7   | Corro Template to notify that CON is compete - Cert Ordered dispatched                                                      | Change of Name | CON Notification | CON-LetterBranding |
      #| CON-Letter8        | Corro Template to notify that CON is compete - Cert Ordered dispatched                                                                           | Change of Name     | CON Notification      | CON-LetterBranding |
      #| CON-Letter9        | Corro Template to notify that CON is closed - Additional information not provided                                                                | Change of Name     | CON Notification      | CON-LetterBranding |
      #| COS-Letter1        | Corro Template for acknowledging receipt of the Change of Sex/Recognised detail  application.                                                    | Change of Sex      | COS Notification      | COS-LetterBranding |
      #| RD-Letter1         | Corro Template for acknowledging receipt of Recognised detail  application.                                                                      | Recognised Details | RD Notification       | COS-LetterBranding |
      #| COS-Letter2        | Corro Template to notify that additional information is required to proceed with COS registration assessment                                     | Change of Sex      | COS Notification      | COS-LetterBranding |
      #| RD-Letter2         | Corro Template to notify that additional information is required to proceed with RD registration assessment                                      | Recognised Details | RD Notification       | COS-LetterBranding |
      #| COS-Letter3        | Corro Template to notify that additional information has not been received during the stipulated time. the application for COS has been closed.  | Change of Sex      | COS Notification      | COS-LetterBranding |
      #| RD-Letter3         | Corro Template to notify that additional information has not been received during the stipulated time. the application for RD has been closed.   | Recognised Details | RD Notification       | COS-LetterBranding |
      #| COS-Letter4        | Corro Template to notify that COS is compete - No Cert                                                                                           | Change of Sex      | COS Notification      | COS-LetterBranding |
      #| RD-Letter4         | Corro Template to notify that RD is compete - No Cert                                                                                            | Recognised Details | RD Notification       | COS-LetterBranding |
      #| COS-Letter5        | Corro Template to notify that COS is compete - Cert Ordered dispatched                                                                           | Change of Sex      | COS Notification      | COS-LetterBranding |
      #| RD-Letter5         | Corro Template to notify that RD is compete - Cert Ordered dispatched                                                                            | Recognised Details | RD Notification       | COS-LetterBranding |
      #| MR-Letter1         | Corro Template to notify that additional information is required to proceed with COS registration assessment                                     | Marriages          | Marriage Notification | MR-LetterBranding  |
      #| MR-Letter2         | Corro Template to notify that NOIM is received but celebrant registration status is inactive                                                     | Marriages          | Marriage Notification | MR-LetterBranding  |
      #| MR-Letter3         | Corro Template to notify that old version of NOIM is used for registration                                                                       | Marriages          | Marriage Notification | MR-LetterBranding  |
      #| MR-Letter4         | Corro Template to notify AGD that NOIM is received from an inactive celebrant                                                                    | Marriages          | Marriage Notification | MR-LetterBranding  |
      #| MR-Letter5         | Corro Template to notify (Bride and Grooom) that MR is compete - No Cert                                                                         | Marriages          | Marriage Notification | MR-LetterBranding  |
      #| MR-Letter6         | Corro Template to notify (Bride and Grooom) that MR is complete - Cert Ordered dispatched                                                        | Marriages          | Marriage Notification | MR-LetterBranding  |
      #| MR-Letter7         | Corro Template to notify that additional information is required to proceed with Marriage Certificate application assessment                     | Transaction        | Application           | MR-LetterBranding  |
      #| CA-Letter1- Births | Corro Template for Notifying that Correction Req. is received                                                                                    | Births             | Amendement Request    | CA-LetterBranding  |
      #| CA-Letter2-Births     | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                     | Births    | Amendement Request | CA-LetterBranding |
      #| CA-Letter3- Births    | Corro Template to notify that additional information has not been received during the stipulated time. the request for corrections has been closed.  | Births    | Amendement Request | CA-LetterBranding |
      #| CA-Letter4- Births    | Corro Template to notify that request for correction/amendment is refused based on assessment                                                        | Births    | Amendement Request | CA-LetterBranding |
      #| CA-Letter5- Births    | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                 | Births    | Amendement Request | CA-LetterBranding |
      #| CA-Letter6- Births    | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                | Births    | Amendement Request | CA-LetterBranding |
      #| CA-Letter7- Births    | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                   | Births    | Amendement Request | CA-LetterBranding |
      #| CA-Letter8- Births    | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                           | Births    | Amendement Request | CA-LetterBranding |
      #| CA-Letter1- Deaths    | Corro Template for Notifying that Correction Req. is received                                                                                        | Deaths    | Amendement Request | CA-LetterBranding |
      #| CA-Letter2-Deaths     | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                     | Deaths    | Amendement Request | CA-LetterBranding |
      #| CA-Letter3- Deaths    | Corro Template to notify that additional information has not been received during the stipulated time. the request for corrections has been closed.  | Deaths    | Amendement Request | CA-LetterBranding |
      #| CA-Letter4- Deaths    | Corro Template to notify that request for correction/amendment is refused based on assessment                                                        | Deaths    | Amendement Request | CA-LetterBranding |
      #| CA-Letter5- Deaths    | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                 | Deaths    | Amendement Request | CA-LetterBranding |
      #| CA-Letter6- Deaths    | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                | Deaths    | Amendement Request | CA-LetterBranding |
      #| CA-Letter7- Deaths    | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                   | Deaths    | Amendement Request | CA-LetterBranding |
      #| CA-Letter8- Deaths    | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                           | Deaths    | Amendement Request | CA-LetterBranding |
      #| CA-Letter1- Marriages | Corro Template for Notifying that Correction Req. is received                                                                                        | Marriages | Amendement Request | CA-LetterBranding |
      #| CA-Letter2-Marriages  | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                     | Marriages | Amendement Request | CA-LetterBranding |
      #| CA-Letter3- Marriages | Corro Template to notify that additional information has not been received during the stipulated time. the request for corrections has been closed.  | Marriages | Amendement Request | CA-LetterBranding |
      #| CA-Letter4- Marriages | Corro Template to notify that request for correction/amendment is refused based on assessment                                                        | Marriages | Amendement Request | CA-LetterBranding |
      #| CA-Letter5- Marriages | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                 | Marriages | Amendement Request | CA-LetterBranding |
      | CA-Letter6- Marriages    | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                    | Marriages          | Amendement Request | CA-LetterBranding    |
      | CA-Letter7- Marriages    | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                       | Marriages          | Amendement Request | CA-LetterBranding    |
      | CA-Letter8- Marriages    | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                               | Marriages          | Amendement Request | CA-LetterBranding    |
      | CA-Letter1- Relationship | Corro Template for Notifying that Correction Req. is received                                                                                            | Relationship       | Amendement Request | CA-LetterBranding    |
      | CA-Letter2-Relationship  | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                         | Relationship       | Amendement Request | CA-LetterBranding    |
      | CA-Letter3- Relationship | Corro Template to notify that additional information has not been received during the stipulated time. the request for corrections has been closed.      | Relationship       | Amendement Request | CA-LetterBranding    |
      | CA-Letter4- Relationship | Corro Template to notify that request for correction/amendment is refused based on assessment                                                            | Relationship       | Amendement Request | CA-LetterBranding    |
      | CA-Letter5- Relationship | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                     | Relationship       | Amendement Request | CA-LetterBranding    |
      | CA-Letter6- Relationship | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                    | Relationship       | Amendement Request | CA-LetterBranding    |
      | CA-Letter7- Relationship | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                       | Relationship       | Amendement Request | CA-LetterBranding    |
      | CA-Letter8- Relationship | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                               | Relationship       | Amendement Request | CA-LetterBranding    |
      | CA-Letter1- CON          | Corro Template for Notifying that Correction Req. is received                                                                                            | Change of Name     | Amendement Request | CA-LetterBranding    |
      | CA-Letter2-CON           | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                         | Change of Name     | Amendement Request | CA-LetterBranding    |
      | CA-Letter3- CON          | Corro Template to notify that additional information has not been received during the stipulated time. the request for corrections has been closed.      | Change of Name     | Amendement Request | CA-LetterBranding    |
      | CA-Letter4- CON          | Corro Template to notify that request for correction/amendment is refused based on assessment                                                            | Change of Name     | Amendement Request | CA-LetterBranding    |
      | CA-Letter5- CON          | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                     | Change of Name     | Amendement Request | CA-LetterBranding    |
      | CA-Letter6- CON          | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                    | Change of Name     | Amendement Request | CA-LetterBranding    |
      | CA-Letter7- CON          | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                       | Change of Name     | Amendement Request | CA-LetterBranding    |
      | CA-Letter8- CON          | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                               | Change of Name     | Amendement Request | CA-LetterBranding    |
      | CA-Letter1- RD           | Corro Template for Notifying that Correction Req. is received                                                                                            | Recognised Details | Amendement Request | CA-LetterBranding    |
      | CA-Letter2-RD            | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                         | Recognised Details | Amendement Request | CA-LetterBranding    |
      | CA-Letter3- RD           | Corro Template to notify that additional information has not been received during the stipulated time. the request for corrections has been closed.      | Recognised Details | Amendement Request | CA-LetterBranding    |
      | CA-Letter4- RD           | Corro Template to notify that request for correction/amendment is refused based on assessment                                                            | Recognised Details | Amendement Request | CA-LetterBranding    |
      | CA-Letter5- RD           | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                     | Recognised Details | Amendement Request | CA-LetterBranding    |
      | CA-Letter6- RD           | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                    | Recognised Details | Amendement Request | CA-LetterBranding    |
      | CA-Letter7- RD           | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                       | Recognised Details | Amendement Request | CA-LetterBranding    |
      | CA-Letter8- RD           | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                               | Recognised Details | Amendement Request | CA-LetterBranding    |
      | DR-Letter4               | Template to notify that DR Certificate is complete                                                                                                       | Transaction        | Application        | DR-LetterBranding    |
      | BR-Letter7               | Corro Template to notify that BR Certificate is complete                                                                                                 | Transaction        | Application        | BR-LetterBranding    |
      | MR-Letter10              | Template to notify that Marriage Ceritifcate is compete                                                                                                  | Transaction        | Application        | MR-LetterBranding    |
      | BRC-Letter8              | Letter Template to  to list exceptions and notify that notify that additional information is required to proceed with Certificate application assessment | Transaction        | Application        | CERTA-LetterBranding |
      