Feature: Creating Correspondence Templates Placeholders for Emails.

  Scenario Outline: Create Email Placeholders
    Given I am on CORE Admin site
    When I want to create a "Email corro" template
    And I want to make the title "<Template Name>" and the description "<Template Description>" and the "<Life Event>" and the "<Document Type>"
    And I want the email to have a the related SMS "<Related SMS Template>" and the Signature Block to be "<Signature block>"
    And I want to make the email subject "<Email Subject>"
    Then I can save the template placeholder

    Examples: 
      | Template Name | Template Description                                                                                                                                    | Life Event | Document Type | Email Subject                                                           | Signature block       |
      #| PT-Email1     | Automated email generated and sent when ePublic user pays for Registry item using BPAY.   |           |               | Email Subject | PT-EmailSignature |
      #| PT-Email2     | Automated email generated amd sent when eRegistry user pays for Registry item using BPAY. |           |               | Email Subject | PT-EmailSignature |
      #| PT-Email3                                                        | Automated email generated when an ePublic user selects to pay for a Registry Item in person                                                                                                                                                                                                    |                |                  | Email Subject                                                           | PT-EmailSignature        |
      #| PT-Email5                                                        | Automated correspondence generated and sent to  a Core user notifying them of the successful processing of the RECall file.                                                                                                                                                                    |                |                  | Email Subject                                                           | PT-EmailSignature        |
      #| PT-Email6                                                        | Automated correspondence generated and sent to a Core user notifying them that the file failed to be processed.                                                                                                                                                                                |                |                  | BPAY payment for your application                                       | PT-EmailSignature        |
      #| PT-Email8                                                        | Manual processing of Westpac payments and upload of csv file with BPAY reference number.  Auto correspondence generated and sent to core user notifying of them the CSV file failed to be processed completely                                                                                 |                |                  | Email Subject                                                           |                          |
      #| PTEmail10                                                        | User selects   Finish transaction   and transction is underpaid.  CBDM user selected generate  Email.  The email is automatically saved in  Application’s Related documents Underpayment”.  Correspondence is sent without user intervention. (IS CBDM core - used by internal BDM users only? |                |                  | Email Subject                                                           |                          |
      #| USM-Email8                                                       | Corro tempate to Notify the stakeholder user that the password has been reset.                                                                                                                                                                                                                 |                |                  | Password has been reset                                                 | USM-EmailSignature       |
      #| BR-Email24                                                       | Corro Template for acknowledge that BRS Part 2 is received (Alert on Parent 1  submission is in place because Parent 1 indicated domestic violence)                                                                                                                                            |                |                  | Registration of Birth - BRS Part 2 Received                             | BR-EmailSignature        |
      #| BR-Email20                                                       | Corro Template for Initial reminder (7 days from receipt of NOB) to birth parent (child born alive) for BRS Submission.                                                                                                                                                                        |                |                  | Reminder for Registration of Birth                                      | BR-EmailSignature        |
      #| BR-Email21                                                       | Corro Template for second reminder (x days from receipt of NOB) to birth parent (child born alive) for BRS Submission.                                                                                                                                                                         |                |                  | Reminder for Registration of Birth                                      | BR-EmailSignature        |
      #| BR-Email22                                                       | Corro Template for initial reminder to birth parent (of still child born child) for BRS Submission.                                                                                                                                                                                            |                |                  | Reminder for Registration of Birth                                      | BR-EmailSignature        |
      #| BR-Email23                                                       | Corro Template for second reminder to birth parent (of still child born child) for BRS Submission.                                                                                                                                                                                             |                |                  | Reminder for Registration of Birth                                      | BR-EmailSignature        |
      #| CON-Email15                                                      | Corro email template advising Declarant 1 to inform Declarant 2                                                                                                                                                                                                 they have not completed Part 2 | Change of Name | CON Notification | Change of Name - Part 2 Incomplete                                      | CON-EmailSignature       |
      #| Email - CON notify Adult Parole Board of completed CON           | Corro Template to notify the Adult Parole Board that a CON has been completed for an offender                                                                                                                                                                                                  | Change of Name | CON Notification | Email Subject                                                           | CON-EmailSignature.doc   |
      #| Email - CON notify Chief Commissioner of Police of completed CON | Corro Template to notify the Chief Commissioner of Police that a CON has been completed for a Registered Sex Offender                                                                                                                                                                          | Change of Name | CON Notification | Email Subject                                                           | CON-EmailSignature.doc   |
      #| Email - Financial defaults/judgements found against applicant    | Corro Template where finacial defaults or judgements have been found. Applicant to provide written sign off / acknowledgement from creditors                                                                                                                                                   | Change of Name | CON Notification | Email Subject                                                           | CON-EmailSignature.doc   |
      #| Email - CON not required and cancelled as Married in Australia   | Corro Template to notify that CON is NOT required as Marriage occurred in Australia. Application cancelled                                                                                                                                                          documents and fee returned | Change of Name | CON Notification | Email Subject                                                           | CON-EmailSignature.doc   |
      #| ED-Email1                                                        | Send out correspondence to respective agent indicating record search is complete and is available on eDiscovery Correspondence template sent to agent indicating record search is complete and available on ediscovery                                                                         |                |                  | Search result available on eDiscovery                                   | eDiscover-EmailSignature |
      #| ED-Email3                                                        | Correspondence template sent to respective agent indicating status check is complete and is available on eDiscovery                                                                                                                                                                            |                |                  | Status check is complete and available on eDiscovery                    | eDiscover-EmailSignature |
      | DE-Email1     | Correspondence tempate for notifying eDes user/applicant that payment for application has been received.                                                |            |               | Data Extract - Payment for Application hs been received                 | DPS-Signature Block   |
      | DE-Email2     | Correspondence template for notifying applicant data extract application has been rejected and reason for decision is included.                         |            |               | Data Extract - Application for Data Extract has been rejected           | DPS-Signature Block   |
      | DE-Email3     | Correspondence template for notifying eDes user that payment is received for the resultset                                                              |            |               | Data Extract - Payment for Data result set is received                  | DPS-Signature Block   |
      | DE-Email3     | Correspondence template generated and to remind applicant payment is required to receive results                                                        |            |               | Data Extract - Payment for Data Extract is required                     | DPS-Signature Block   |
      | DE-Email5     | Correspondence template informing applicant of the time to pay for the result set has expired Data Extract Application has been cancelled.              |            |               | Data Extract - Application for Data Extract is Expired                  | DPS-Signature Block   |
      | DR- Email11   | Template to advise MCCD signed by wrong doctor                                                                                                          | Deaths     | COD           | MCCD not signed.                                                        | DR-SignatureBlock.doc |
      | DR-Email12    | Template to advise requirements for overseas death                                                                                                      | Deaths     | DRS           | Requirements for registering overseas death                             | DR-SignatureBlock.doc |
      | FH-Email3     | Template for sending link  to zip file of all   Uncertified Downloadable Copies  .                                                                      |            |               | eFamily History- Link  to  Uncertified Downloadable Copies.             | FH-SignatureBlock     |
      | EREG-Email1   | Template for sending email with URL payment link for stakeholder to make payment                                                                        |            |               | eRegistry - Link for payment                                            | EREG-Signature Block  |
      | EREG-Email3   | Correspondence template sent to a list of email id addresses advising of the errors that occurred during processing of NOBs from the XML file.          |            |               | Processing Notification of Births - Errors have occurred please address | EREG-Signature Block  |
      | POI-Email1    | Correspondenc template to send details to applicants about performing POI later. It includes hyperlink for 'Do POI later' and message ID and Enquiry ID |            |               | Online Proof of Idnetity - Link for completing POI                      | POI-Signature block   |
