Feature: Creating Correspondence Templates Placeholders for Emails.

  Scenario Outline: Create Email Placeholders
    Given I am on CORE Admin site
    When I want to create a "Email corro" template
    And I want to make the title "<Template Name>" and the description "<Template Description>" and the "<Life Event>" and the "<Document Type>"
    And I want the email to have a the related SMS "<Related SMS Template>" and the Signature Block to be "<Signature block>"
    And I want to make the email subject "<Email Subject>"
    Then I can save the template placeholder

    Examples: 
      | Template Name | Template Description                                                                                                  | Life Event | Document Type | Related SMS Template | Email Subject                                 | Signature block   |
      #| BR-Email1     | Corro Template for Notifying that BRS Part 1 is received                                                       |            |               | GR-SMS1              | Registration of Birth - BRS Part 1 Received             | BR-EmailSignature |
      #| BR-Email2     | Corro Template for requesting BRS Part 2                                                                       |            |               | GR-SMS1              | Registration of Birth - BRS Part 2 required             | BR-EmailSignature |
      #| BR-Email2A    | Corro Template for resend for requesting BRS Part 2                                                            |            |               | GR-SMS1              | Registration of Birth - BRS Part 2 required             | BR-EmailSignature |
      #| BR-Email3     | Corro Template for acknowledge that BRS Part 2 is received                                                     |            |               | GR-SMS1              | Registration of Birth - BRS Part 2 Received             | BR-EmailSignature |
      #| BR-Email4     | Corro Template to notify that BR is compete - No Cert                                                          |            |               | GR-SMS1              | Registration of Birth - Completed                       | BR-EmailSignature |
      #| BR-Email5     | Corro Template to notify that BR is compete - Cert Ordered dispatched                                          |            |               | GR-SMS1              | Registration of Birth - Completed                       | BR-EmailSignature |
      #| BR-Email6     | Corro Template to notify that additional information is required to proceed with Birth Registration assessment | Births     | BRS           | GR-SMS1              | Registration of Birth - Additional Information required | BR-EmailSignature |
      #| BR-Email9     | Corro Template to advise that details of the donor treatment is not held in Victoria.                          | Births     | BRS           | GR-SMS1              | Registration of Birth - Donor details                   | BR-EmailSignature |
      #| BR-Email10               | Corro Template to advise that Child Name is a prohibited name                                                                                                                           | Births             | BRS                   | GR-SMS1              | Registration of Birth - prohibited name                                                           | BR-EmailSignature     |
      #| BR-Email11               | Corro Template to advise that Parentage dispute is indicated on BRS submission                                                                                                          | Births             | BRS                   | GR-SMS1              | Registration of Birth - Parentage Dispute                                                         | BR-EmailSignature     |
      #| BR-Email12               | Corro Template to advise DHS to submit BRS                                                                                                                                              | Births             | BRS                   | GR-SMS1              | Registration of Birth - DHS request                                                               | BR-EmailSignature     |
      #| BR-Email13               | Corro Template to inform that BRS Part 2 is not yet received                                                                                                                            | Births             | BRS                   | GR-SMS1              | Registration of Birth - Awaiting BRS Part 2                                                       | BR-EmailSignature     |
      #| BR-Email14               | Corro Template to inform that BR is registered without Parent 2 details                                                                                                                 |                    |                       | GR-SMS1              | Registration of Birth - BR completed without Parent 2                                             | BR-EmailSignature     |
      #| BR-Email15               | Corro Template to inform that information in BRS and NOB is not same                                                                                                                    | Births             | BRS                   | GR-SMS1              | Registration of Birth - Information not complete                                                  | BR-EmailSignature     |
      #| BR-Email16               | Corro Template to notify adoptive parents that BR is compete - No Cert                                                                                                                  |                    |                       | GR-SMS1              | Registration of Birth - Completed                                                                 | BR-EmailSignature     |
      #| BR-Email17               | Corro Template to notify commissioning parents to submit BRS                                                                                                                            |                    |                       | GR-SMS1              | Registration of Birth - BRS submission required                                                   | BR-EmailSignature     |
      #| BR-Email18               | Corro Template to notify adoptive parents that BR is compete - No Cert                                                                                                                  |                    |                       | GR-SMS1              | Registration of Birth - Completed                                                                 | BR-EmailSignature     |
      #| BR-Email19               | Corro Template to notify adoptive parents that BR is compete - No Cert                                                                                                                  |                    |                       | GR-SMS1              | Registration of Birth - Completed                                                                 | BR-EmailSignature     |
      | GR-Email6     | Corro Tempate for notifying Party 1 that this request has been cancelled due to no response for Part II from Party 2. | Births     | BRS           | GR-SMS1              | Cancellation of the your request : Ref $$CONN | BR-EmailSignature |
      #| DR-Email1                | Template to Correspond with the 'Informant' provided by the Funeral Director advising the completion of registration and Death certificate  can be ordered.                             |                    |                       | GR-SMS1              | Email subject                                                                                     | DR-SignatureBlock     |
      #| DR-Email2                | Template to Correspond with the 'Informant' provided by the Funeral Director advising the completion of registration and Death certificate will be mailed.                              |                    |                       | GR-SMS1              | Email subject                                                                                     | DR-SignatureBlock     |
      #| DR-Email3                | Template to notify that additional information is required to proceed with Death Registration assessment                                                                                | Deaths             | DRS                   | GR-SMS1              | Email subject                                                                                     | DR-SignatureBlock     |
      #| DR-Email6                | Template to request FD to submit DRS                                                                                                                                                    | Deaths             | COD                   | GR-SMS1              | Email subject                                                                                     | DR-SignatureBlock     |
      #| DR-Email7                | Template to request Doctor to submit COD                                                                                                                                                | Deaths             | DRS                   |                      | Email subject                                                                                     | DR-SignatureBlock     |
      #| DR-Email8                | Template to request Family Members to submit DRS                                                                                                                                        | Deaths             | COD                   |                      | Email subject                                                                                     | DR-SignatureBlock     |
      #| DR-Email9                | Template to request Doctor to submit COD                                                                                                                                                | Deaths             | DRS                   |                      | Email subject                                                                                     | DR-SignatureBlock     |
      #| DR-Email10               | Template to Corrospond with Doctor (MCCPD) and Hospital (NOB) to advise that information on MCCPD inconsistent with NOB or BR or BRS                                                    | Births             | BRS                   |                      | Email subject                                                                                     | DR-SignatureBlock     |
      #| GR-EMAIL1                | Template for sending link to the draft request form for the guest user.                                                                                                                 |                    |                       | GR-SMS1              | Link to your saved form                                                                           |                       |
      #| GR-Email2                | Corro Tempate for sending submitted order reference with details on perfoming DPOI or POI in person.                                                                                    |                    |                       |                      | POI required for your submitted order                                                             |                       |
      #| RR-Email1                | Corro Template for Notifying that Relationship Applicant 1 submission is received                                                                                                       |                    |                       | GR-SMS1              | Email subject                                                                                     | RR-SignatureBlock     |
      #| RR-Email2                | Corro Template for requesting Relationship Part 2                                                                                                                                       |                    |                       | GR-SMS1              | Email subject                                                                                     | RR-SignatureBlock     |
      #| RR-Email2A               | Corro Template for requesting Relationship Part 2  (Resend)                                                                                                                             |                    |                       | GR-SMS1              | Email subject                                                                                     | RR-SignatureBlock     |
      #| RR-Email3                | Corro Template for acknowledge that Applicant 2 submission is received                                                                                                                  | Relationship       | RLR Notification      | GR-SMS1              | Email subject                                                                                     | RR-SignatureBlock     |
      #| RR-Email4                | Corro Template to Notify that Cooling off period has started                                                                                                                            |                    |                       | GR-SMS1              | Email subject                                                                                     | RR-SignatureBlock     |
      #| RR-Email18               | Corr Template to Notify  to notify that additional information is required to proceed with Relationship Registration                                                                    | Relationship       | RLR Notification      | GR-SMS1              | Registration of Relationship - Additional Information required                                    | RR-SignatureBlock     |
      #| RR-Email5                | Corr Template to Notify that additional documentation / information is not received and therefore the application is closed                                                             |                    |                       | GR-SMS1              | Email subject                                                                                     | RR-SignatureBlock     |
      #| RR-Email6                | Corr Template to acknowledge that a witdrawal request for the relationship application has been received and processed                                                                  |                    |                       | GR-SMS1              | Email subject                                                                                     | RR-SignatureBlock     |
      #| RR-Email7                | Corr Template to notify Party 2 that a witdrawal request for the relationship application has been received and processed                                                               |                    |                       | GR-SMS1              | Email subject                                                                                     | RR-SignatureBlock     |
      #| RR-Email8                | Corro Template to notify that RR is compete - No Cert                                                                                                                                   |                    |                       | GR-SMS1              | Email subject                                                                                     | RR-SignatureBlock     |
      #| RR-Email9                | Corro Template to notify that RR is compete - Cert Ordered dispatched                                                                                                                   |                    |                       | GR-SMS1              | Email subject                                                                                     | RR-SignatureBlock     |
      #| RR-Email10               | Corro Template for Notifying that Relationship Applicant 1 submission is received                                                                                                       |                    |                       | GR-SMS1              | Email subject                                                                                     | RR-SignatureBlock     |
      #| RR-Email11               | Corro Template for requesting Revocation Part 2                                                                                                                                         |                    |                       | GR-SMS1              | Email subject                                                                                     | RR-SignatureBlock     |
      #| RR-Email12               | Corro Template for acknowledge that Applicant 2 submission for revocation is received                                                                                                   |                    |                       | GR-SMS1              | Email subject                                                                                     | RR-SignatureBlock     |
      #| RR-Email13               | Corr Template to acknowledge that a witdrawal request for the relationship revocation has been received and processed                                                                   |                    |                       | GR-SMS1              | Email subject                                                                                     | RR-SignatureBlock     |
      #| RR-Email14               | Corr Template to acknowledge that a witdrawal request for the relationship revocation has been received and processed                                                                   |                    |                       | GR-SMS1              | Email subject                                                                                     | RR-SignatureBlock     |
      #| RR-Email15               | Corro Template to notify that revocation  is compete - No Cert                                                                                                                          |                    |                       | GR-SMS1              | Email subject                                                                                     | RR-SignatureBlock     |
      #| RR-Email16               | Corro Template to Notify that Cooling off period has started                                                                                                                            |                    |                       | GR-SMS1              | Email subject                                                                                     | RR-SignatureBlock     |
      #| GR-Email3                | Corro Tempate for notifying Party 1 that this request has been cancelled due to no response for Part II from Party 2.                                                                   |                    |                       | GR-SMS1              | Cancellation of the your request : Ref $$RLNN                                                     | RR-SignatureBlock     |
      #| CON-Email1               | Corro Template for Notifying that CON application for Vic Born Adult is received                                                                                                        |                    |                       | GR-SMS1              | Change of Name - Application Received                                                             | CON-EmailSignature    |
      #| CON-Email2               | Corro Template for Notifying that CON application for Non-Vic Born Adult is received                                                                                                    |                    |                       | GR-SMS1              | Change of Name - Application Received                                                             | CON-EmailSignature    |
      #| CON-Email3               | Corro Template for requesting CON Part 2                                                                                                                                                |                    |                       | GR-SMS1              | Change of Name  (Child)- Part 2 submission required                                               | CON-EmailSignature    |
      #| CON-Email4               | Corro Template for requesting CON Part 2                                                                                                                                                | Change of Name     | CON Notification      | GR-SMS1              | Change of Name  (Child)- Part 2 submission required                                               | CON-EmailSignature    |
      #| CON-Email5               | Corro Template to notify that additional information is required to proceed with Registration assessment                                                                                |                    |                       | GR-SMS1              | Registration of CON - Additional Information required. Ref $$ CONN ID                             | CON-EmailSignature    |
      #| CON-Email6               | Corro Template to notify that CON is compete - No Cert                                                                                                                                  |                    |                       | GR-SMS1              | Registration of CON - Completed                                                                   | CON-EmailSignature    |
      #| CON-Email7               | Corro Template to notify that CON is compete - Cert Ordered dispatched                                                                                                                  |                    |                       | GR-SMS1              | Registration of CON - Completed                                                                   | CON-EmailSignature    |
      #| CON-Email8               | Corro Template to notify that CON is compete - Cert Ordered dispatched                                                                                                                  |                    |                       | GR-SMS1              | Registration of CON - Completed                                                                   | CON-EmailSignature    |
      #| CON-Email9               | Corro Template to notify that CON is closed - Additional information not provided                                                                                                       |                    |                       | GR-SMS1              | Application for  CON - Closed                                                                     | CON-EmailSignature    |
      #| GR-Email5                | Corro Tempate for notifying Party 1 that this request has been cancelled due to no response for Part II from Party 2.                                                                   |                    |                       | GR-SMS1              | Cancellation of the your request : Ref $$CONN                                                     | CON-EmailSignature    |
      #| COS-Email1               | Corro Template for acknowledging receipt of the Change of Sex/Recognised detail  application.                                                                                           |                    |                       | GR-SMS1              | Change of Sex - Application Received                                                              | COS-EmailSignature    |
      #| RD-Email1                | Corro Template for acknowledging receipt of Recognised detail  application.                                                                                                             |                    |                       | GR-SMS1              | Recognised Details - Application Received                                                         | COS-EmailSignature    |
      #| COS-Email2               | Corro Template to notify that additional information is required to proceed with COS registration assessment                                                                            | Change of Sex      | COS Notification      | GR-SMS1              | Registration of COS - Additional Information required                                             | COS-EmailSignature    |
      #| RD-Email2                | Corro Template to notify that additional information is required to proceed with RD registration assessment                                                                             | Recognised Details | RD Notification       | GR-SMS1              | Registration of RD - Additional Information required                                              | COS-EmailSignature    |
      #| COS-Email3               | Corro Template to notify that additional information has not been received during the stipulated time. the application for COS has been closed.                                         |                    |                       | GR-SMS2              | Registration of Change of Sex  - Additional information not received                              | COS-EmailSignature    |
      #| RD-Email3                | Corro Template to notify that additional information has not been received during the stipulated time. the application for RD has been closed.                                          |                    |                       | GR-SMS2              | Registration of Recongnised Details  - Additional information not received                        | COS-EmailSignature    |
      #| COS-Email4               | Corro Template to notify that COS is compete - No Cert                                                                                                                                  | Change of Sex      | COS Notification      | GR-SMS1              | Registration of COS  - Completed                                                                  | COS-EmailSignature    |
      #| RD-Email4                | Corro Template to notify that RD is compete - No Cert                                                                                                                                   | Recognised Details | RD Notification       | GR-SMS1              | Registration of RD   - Completed                                                                  | COS-EmailSignature    |
      #| COS-Email5               | Corro Template to notify that COS is compete - Cert Ordered dispatched                                                                                                                  | Change of Sex      | COS Notification      | GR-SMS1              | Registration of COS  - Completed                                                                  | COS-EmailSignature    |
      #| RD-Email5                | Corro Template to notify that RD is compete - Cert Ordered dispatched                                                                                                                   | Recognised Details | RD Notification       | GR-SMS1              | Registration of RD   - Completed                                                                  | COS-EmailSignature    |
      #| MR-Email1                | Corro Template to notify that additional information is required to proceed with Marriage registration assessment                                                                       | Marriages          | Marriage Notification | GR-SMS1              | Registration of Marriage - Additional Information required                                        | MR-EmailSignature     |
      #| MR-Email2                | Corro Template to notify that NOIM is received but celebrant registration status is inactive                                                                                            | Marriages          | Marriage Notification | GR-SMS1              | Registration of Marriage - Celebrant Inactive                                                     | MR-EmailSignature     |
      #| MR-Email3                | Corro Template to notify that old version of NOIM is used for registration                                                                                                              | Marriages          | Marriage Notification | GR-SMS1              | Registration of Marriage - Celebrant Inactive                                                     | MR-EmailSignature     |
      #| MR-Email4                | Corro Template to notify AGD that NOIM is received from an inactive celebrant                                                                                                           | Marriages          | Marriage Notification |                      | Registration of Marriage - Celebrant Inactive                                                     | MR-EmailSignature     |
      #| MR-Email5                | Corro Template to notify (Bride and Grooom) that MR is compete - No Cert                                                                                                                |                    |                       | GR-SMS1              | Registration of Marriage   - Completed                                                            | MR-EmailSignature     |
      #| MR-Email6                | Corro Template to notify (Bride and Grooom) that MR is complete - Cert Ordered dispatched                                                                                               |                    |                       | GR-SMS1              | Registration of Marriage  - Completed                                                             | MR-EmailSignature     |
      #| MR-Email7                | Corro Template to notify that additional information is required to proceed with Marriage Certificate application assessment                                                            | Transaction        | Application           | GR-SMS1              | Marriage Certificate Application - Additional Information required                                | MR-EmailSignature     |
      #| MR-Email8                | Corro Template to notify the receiving Celebrant that NOIM(s) are transferred to them                                                                                                   |                    |                       |                      | Transfer to NOIM                                                                                  | MR-EmailSignature     |
      #| MR-Email9                | Corro Template to notify the Celebrant that NOIM(s) are transferred to another Celebrant                                                                                                |                    |                       |                      | Transfer to NOIM                                                                                  | MR-EmailSignature     |
      #| VMR-Email1               | Corro Template for Acknowledge that a request for ceremony booking is received                                                                                                          |                    |                       | GR-SMS1              | Marriage Ceremony booking - booking request received                                              | VMR-EmailSignature    |
      #| VMR-Email2               | Corro Template to notify that additional information is required to proceed with Marriage booking                                                                                       | Marriages          | Marriage - eBooking   | GR-SMS1              | Marriage Ceremony booking - Additional Information required                                       | VMR-EmailSignature    |
      #| VMR-Email3               | Corro Template to notify that additional information has not been received during the stipulated time. the booking is now cancelled                                                     | Marriages          | Marriage - eBooking   | GR-SMS1              | Marriage Ceremony booking - Additional Information not received                                   | VMR-EmailSignature    |
      #| VMR-Email4               | Corro Template to notify that required payment has not been received during the stipulated time. the booking is now cancelled                                                           | Marriages          | Marriage - eBooking   | GR-SMS1              | Marriage Ceremony booking - Payment not received                                                  | VMR-EmailSignature    |
      #| VMR-Email5               | Corro Template to notify  that a request for ceremony booking is confirmed                                                                                                              | Marriages          | Marriage - eBooking   | GR-SMS1              | Marriage Ceremony booking - booking confirmed                                                     | VMR-EmailSignature    |
      #| VMR-Email6               | Corro Template to notify that the shortening of notice for Marriage has been declined.                                                                                                  | Marriages          | Marriage - eBooking   | GR-SMS1              | Marriage Ceremony booking - Shortening of notice period declined                                  | VMR-EmailSignature    |
      #| VMR-Email7               | Corro Template to notify that the shortening of notice period for Marriage has been accepted.                                                                                           | Marriages          | Marriage - eBooking   | GR-SMS1              | Marriage Ceremony booking - Shortening of notice period declined                                  | VMR-EmailSignature    |
      #| CA-Email1- Births        | Corro Template for Notifying that Correction Req. is received                                                                                                                           | Births             | Amendement Request    | GR-SMS1              | Correction/Amendment  Request Received. Ref: $$CorrectionRequestRef                               | CA-EmailSignature     |
      #| CA-Letter1- Births       | Corro Template for Notifying that Correction Req. is received                                                                                                                           | Births             | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email2-Births         | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                                                        | Births             | Amendement Request    | GR-SMS1              | Correction/Amendment  Additional Information  Required Ref:$$CorrectionRequestRef                 | CA-EmailSignature.doc |
      #| CA-Letter2-Births        | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                                                        | Births             | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email3- Births        | Corro Template to notify that additional information has not been received during the stipulated time. the request for corrections has been closed.                                     | Births             | Amendement Request    | GR-SMS1              | Correction/Amendment  Request  - Additional Information required. $$CorrectionRequestRef          | CA-EmailSignature     |
      #| CA-Letter3- Births       | Corro Template to notify that additional information has not been received during the stipulated time. the request for corrections has been closed.                                     | Births             | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email4- Births        | Corro Template to notify that request for correction/amendment is refused based on assessment                                                                                           | Births             | Amendement Request    | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request refused. Ref:$$CorrectionRequestRef  | CA-EmailSignature     |
      #| CA-Letter4- Births       | Corro Template to notify that request for correction/amendment is refused based on assessment                                                                                           | Births             | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email5- Births        | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                                                    | Births             | Amendement Request    | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request accepted. Ref:$$CorrectionRequestRef | CA-EmailSignature     |
      #| CA-Letter5- Births       | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                                                    | Births             | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email6- Births        | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                                                   |                    |                       | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request accepted. Ref:$$CorrectionRequestRef | CA-EmailSignature     |
      #| CA-Letter6- Births       | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                                                   | Births             | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email7- Births        | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                                                      | Births             | Amendement Request    | GR-SMS1              | Correction/Amendment   - Completed Ref:$$CorrectionRequestRef                                     | CA-EmailSignature     |
      #| CA-Letter7- Births       | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                                                      | Births             | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email8- Births        | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                                                              | Births             | Amendement Request    | GR-SMS1              | Correction/Amendment   - Completed. Ref:$$CorrectionRequestRef                                    | CA-EmailSignature     |
      #| CA-Letter8- Births       | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                                                              | Births             | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email1- Deaths        | Corro Template for Notifying that Correction Req. is received                                                                                                                           | Deaths             | Amendement Request    | GR-SMS1              | Correction/Amendment  Request Received. Ref: $$CorrectionRequestRef                               | CA-EmailSignature     |
      #| CA-Letter1- Deaths       | Corro Template for Notifying that Correction Req. is received                                                                                                                           | Deaths             | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email2-Deaths         | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                                                        | Deaths             | Amendement Request    | GR-SMS1              | Correction/Amendment  Additional Information  Required Ref:$$CorrectionRequestRef                 | CA-EmailSignature.doc |
      #| CA-Letter2-Deaths        | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                                                        | Deaths             | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email3- Deaths        | Corro Template to notify that additional information has not been received during the stipulated time. the request for corrections has been closed.                                     | Deaths             | Amendement Request    | GR-SMS1              | Correction/Amendment  Request  - Additional Information required. $$CorrectionRequestRef          | CA-EmailSignature     |
      #| CA-Letter3- Deaths       | Corro Template to notify that additional information has not been received during the stipulated time. the request for corrections has been closed.                                     | Deaths             | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email4- Deaths        | Corro Template to notify that request for correction/amendment is refused based on assessment                                                                                           | Deaths             | Amendement Request    | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request refused. Ref:$$CorrectionRequestRef  | CA-EmailSignature     |
      #| CA-Letter4- Deaths       | Corro Template to notify that request for correction/amendment is refused based on assessment                                                                                           | Deaths             | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email5- Deaths        | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                                                    | Deaths             | Amendement Request    | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request accepted. Ref:$$CorrectionRequestRef | CA-EmailSignature     |
      #| CA-Letter5- Deaths       | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                                                    | Deaths             | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email6- Deaths        | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                                                   |                    |                       | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request accepted. Ref:$$CorrectionRequestRef | CA-EmailSignature     |
      #| CA-Letter6- Deaths       | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                                                   | Deaths             | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email7- Deaths        | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                                                      | Deaths             | Amendement Request    | GR-SMS1              | Correction/Amendment   - Completed Ref:$$CorrectionRequestRef                                     | CA-EmailSignature     |
      #| CA-Letter7- Deaths       | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                                                      | Deaths             | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email8- Deaths        | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                                                              | Deaths             | Amendement Request    | GR-SMS1              | Correction/Amendment   - Completed. Ref:$$CorrectionRequestRef                                    | CA-EmailSignature     |
      #| CA-Letter8- Deaths       | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                                                              | Deaths             | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email1- Marriages     | Corro Template for Notifying that Correction Req. is received                                                                                                                           | Marriages          | Amendement Request    | GR-SMS1              | Correction/Amendment  Request Received. Ref: $$CorrectionRequestRef                               | CA-EmailSignature     |
      #| CA-Letter1- Marriages    | Corro Template for Notifying that Correction Req. is received                                                                                                                           | Marriages          | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email2-Marriages      | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                                                        | Marriages          | Amendement Request    | GR-SMS1              | Correction/Amendment  Additional Information  Required Ref:$$CorrectionRequestRef                 | CA-EmailSignature.doc |
      #| CA-Letter2-Marriages     | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                                                        | Marriages          | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email3- Marriages     | Corro Template to notify that additional information has not been received during the stipulated time. the request for corrections has been closed.                                     | Marriages          | Amendement Request    | GR-SMS1              | Correction/Amendment  Request  - Additional Information required. $$CorrectionRequestRef          | CA-EmailSignature     |
      #| CA-Letter3- Marriages    | Corro Template to notify that additional information has not been received during the stipulated time. the request for corrections has been closed.                                     | Marriages          | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email4- Marriages     | Corro Template to notify that request for correction/amendment is refused based on assessment                                                                                           | Marriages          | Amendement Request    | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request refused. Ref:$$CorrectionRequestRef  | CA-EmailSignature     |
      #| CA-Letter4- Marriages    | Corro Template to notify that request for correction/amendment is refused based on assessment                                                                                           | Marriages          | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email5- Marriages     | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                                                    | Marriages          | Amendement Request    | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request accepted. Ref:$$CorrectionRequestRef | CA-EmailSignature     |
      #| CA-Letter5- Marriages    | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                                                    | Marriages          | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email6- Marriages     | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                                                   |                    |                       | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request accepted. Ref:$$CorrectionRequestRef | CA-EmailSignature     |
      #| CA-Letter6- Marriages    | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                                                   | Marriages          | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email7- Marriages     | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                                                      | Marriages          | Amendement Request    | GR-SMS1              | Correction/Amendment   - Completed Ref:$$CorrectionRequestRef                                     | CA-EmailSignature     |
      #| CA-Letter7- Marriages    | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                                                      | Marriages          | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email8- Marriages     | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                                                              | Marriages          | Amendement Request    | GR-SMS1              | Correction/Amendment   - Completed. Ref:$$CorrectionRequestRef                                    | CA-EmailSignature     |
      #| CA-Letter8- Marriages    | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                                                              | Marriages          | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email1- Relationship  | Corro Template for Notifying that Correction Req. is received                                                                                                                           | Relationship       | Amendement Request    | GR-SMS1              | Correction/Amendment  Request Received. Ref: $$CorrectionRequestRef                               | CA-EmailSignature     |
      #| CA-Letter1- Relationship | Corro Template for Notifying that Correction Req. is received                                                                                                                           | Relationship       | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email2-Relationship   | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                                                        | Relationship       | Amendement Request    | GR-SMS1              | Correction/Amendment  Additional Information  Required Ref:$$CorrectionRequestRef                 | CA-EmailSignature.doc |
      #| CA-Letter2-Relationship  | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                                                        | Relationship       | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email3- Relationship  | Corro Template to notify that additional information has not been received during the stipulated time. the request for corrections has been closed.                                     | Relationship       | Amendement Request    | GR-SMS1              | Correction/Amendment  Request  - Additional Information required. $$CorrectionRequestRef          | CA-EmailSignature     |
      #| CA-Letter3- Relationship | Corro Template to notify that additional information has not been received during the stipulated time. the request for corrections has been closed.                                     | Relationship       | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email4- Relationship  | Corro Template to notify that request for correction/amendment is refused based on assessment                                                                                           | Relationship       | Amendement Request    | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request refused. Ref:$$CorrectionRequestRef  | CA-EmailSignature     |
      #| CA-Letter4- Relationship | Corro Template to notify that request for correction/amendment is refused based on assessment                                                                                           | Relationship       | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email5- Relationship  | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                                                    | Relationship       | Amendement Request    | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request accepted. Ref:$$CorrectionRequestRef | CA-EmailSignature     |
      #| CA-Letter5- Relationship | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                                                    | Relationship       | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email6- Relationship  | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                                                   |                    |                       | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request accepted. Ref:$$CorrectionRequestRef | CA-EmailSignature     |
      #| CA-Letter6- Relationship | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                                                   | Relationship       | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email7- Relationship  | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                                                      | Relationship       | Amendement Request    | GR-SMS1              | Correction/Amendment   - Completed Ref:$$CorrectionRequestRef                                     | CA-EmailSignature     |
      #| CA-Letter7- Relationship | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                                                      | Relationship       | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email8- Relationship  | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                                                              | Relationship       | Amendement Request    | GR-SMS1              | Correction/Amendment   - Completed. Ref:$$CorrectionRequestRef                                    | CA-EmailSignature     |
      #| CA-Letter8- Relationship | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                                                              | Relationship       | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email1- CON           | Corro Template for Notifying that Correction Req. is received                                                                                                                           | Change of Name     | Amendement Request    | GR-SMS1              | Correction/Amendment  Request Received. Ref: $$CorrectionRequestRef                               | CA-EmailSignature     |
      #| CA-Letter1- CON          | Corro Template for Notifying that Correction Req. is received                                                                                                                           | Change of Name     | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email2-CON            | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                                                        | Change of Name     | Amendement Request    | GR-SMS1              | Correction/Amendment  Additional Information  Required Ref:$$CorrectionRequestRef                 | CA-EmailSignature.doc |
      #| CA-Letter2-CON           | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                                                        | Change of Name     | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email3- CON           | Corro Template to notify that additional information has not been received during the stipulated time. the request for corrections has been closed.                                     | Change of Name     | Amendement Request    | GR-SMS1              | Correction/Amendment  Request  - Additional Information required. $$CorrectionRequestRef          | CA-EmailSignature     |
      #| CA-Letter3- CON          | Corro Template to notify that additional information has not been received during the stipulated time. the request for corrections has been closed.                                     | Change of Name     | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email4- CON           | Corro Template to notify that request for correction/amendment is refused based on assessment                                                                                           | Change of Name     | Amendement Request    | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request refused. Ref:$$CorrectionRequestRef  | CA-EmailSignature     |
      #| CA-Letter4- CON          | Corro Template to notify that request for correction/amendment is refused based on assessment                                                                                           | Change of Name     | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email5- CON           | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                                                    | Change of Name     | Amendement Request    | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request accepted. Ref:$$CorrectionRequestRef | CA-EmailSignature     |
      #| CA-Letter5- CON          | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                                                    | Change of Name     | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email6- CON           | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                                                   |                    |                       | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request accepted. Ref:$$CorrectionRequestRef | CA-EmailSignature     |
      #| CA-Letter6- CON          | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                                                   | Change of Name     | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email7- CON           | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                                                      | Change of Name     | Amendement Request    | GR-SMS1              | Correction/Amendment   - Completed Ref:$$CorrectionRequestRef                                     | CA-EmailSignature     |
      #| CA-Letter7- CON          | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                                                      | Change of Name     | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email8- CON           | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                                                              | Change of Name     | Amendement Request    | GR-SMS1              | Correction/Amendment   - Completed. Ref:$$CorrectionRequestRef                                    | CA-EmailSignature     |
      #| CA-Letter8- CON          | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                                                              | Change of Name     | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email1- RD            | Corro Template for Notifying that Correction Req. is received                                                                                                                           | Recognised Details | Amendement Request    | GR-SMS1              | Correction/Amendment  Request Received. Ref: $$CorrectionRequestRef                               | CA-EmailSignature     |
      #| CA-Letter1- RD           | Corro Template for Notifying that Correction Req. is received                                                                                                                           | Recognised Details | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email2-RD             | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                                                        | Recognised Details | Amendement Request    | GR-SMS1              | Correction/Amendment  Additional Information  Required Ref:$$CorrectionRequestRef                 | CA-EmailSignature.doc |
      #| CA-Letter2-RD            | Corro Template to notify that additional information is required to proceed with Amendment/Correction assessment                                                                        | Recognised Details | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email3- RD            | Corro Template to notify that additional information has not been received during the stipulated time. the request for corrections has been closed.                                     | Recognised Details | Amendement Request    | GR-SMS1              | Correction/Amendment  Request  - Additional Information required. $$CorrectionRequestRef          | CA-EmailSignature     |
      #| CA-Letter3- RD           | Corro Template to notify that additional information has not been received during the stipulated time. The request for corrections has been closed.                                     | Recognised Details | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email4- RD            | Corro Template to notify that request for correction/amendment is refused based on assessment                                                                                           | Recognised Details | Amendement Request    | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request refused. Ref:$$CorrectionRequestRef  | CA-EmailSignature     |
      #| CA-Letter4- RD           | Corro Template to notify that request for correction/amendment is refused based on assessment                                                                                           | Recognised Details | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email5- RD            | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                                                    | Recognised Details | Amendement Request    | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request accepted. Ref:$$CorrectionRequestRef | CA-EmailSignature     |
      #| CA-Letter5- RD           | Corro Template to notify that request for correction/amendment is accepted  based on assessment. No payment required                                                                    | Recognised Details | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email6- RD            | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                                                   |                    |                       | GR-SMS1              | Correction/Amendment Request  - Assessment complete. Request accepted. Ref:$$CorrectionRequestRef | CA-EmailSignature     |
      #| CA-Letter6- RD           | Corro Template to notify that request for correction/amendment is accepted  based on assessment - Payment is required                                                                   | Recognised Details | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email7- RD            | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                                                      | Recognised Details | Amendement Request    | GR-SMS1              | Correction/Amendment   - Completed Ref:$$CorrectionRequestRef                                     | CA-EmailSignature     |
      #| CA-Letter7- RD           | Corro Template to notify Correction/Amendment is compete - No Cert                                                                                                                      | Recognised Details | Amendement Request    |                      |                                                                                                   |                       |
      #| CA-Email8- RD            | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                                                              | Recognised Details | Amendement Request    | GR-SMS1              | Correction/Amendment   - Completed. Ref:$$CorrectionRequestRef                                    | CA-EmailSignature     |
      #| CA-Letter8- RD           | Corro Template to notify Correction/Amendment is compete - Cert Dispatched                                                                                                              | Recognised Details | Amendement Request    |                      |                                                                                                   |                       |
      #| USM-Email1               | Corro Template for Acknowledge that a request is received for becoming a stakeholder/service partner                                                                                    |                    |                       | N/A                  | Email Subject                                                                                     | USM-EmailSignature    |
      #| USM-Email2               | Corro Template to advise that a request for becoming a stakeholder/service partner is NOT accepted                                                                                      |                    |                       | N/A                  | Request for registration as a service partner/stakeholder organisation - Rejected                 | USM-EmailSignature    |
      #| USM-Email3               | Corro Template to notifiy users that request is approved and to complete profile details to progress the  registration.                                                                 |                    |                       | N/A                  | Request for registration accpeted.                                                                | USM-EmailSignature    |
      #| USM-Email4               | Corro Template to notifiy users that registration is complete and they have access to relevant areas on the service partner website. (eRegistry)                                        |                    |                       | N/A                  | Registration Complete                                                                             | USM-EmailSignature    |
      #| USM-Email5               | Corro Template to advise that a request for becoming a stakeholder/service partner is accepted. - A link to complete stakeholder representative details is sent in this correspondence. |                    |                       | N/A                  | Request for registration as a service partner/stakeholder organisation - Accepted                 | USM-EmailSignature    |
      #| USM-Email6               | Corro Template to notifiy a ePublic user that registration is complete. The correspondence includes the password that the user must use to login..                                      |                    |                       | N/A                  | ePublic - Registration Complete                                                                   | USM-EmailSignature    |
      #| USM-Email7               | Corro Template to notifiy a service partner user that they have changed their password.                                                                                                 |                    |                       |                      | Service Partner Registration - Password change                                                    | USM-EmailSignature    |
      #| FH-EMAIL1                | Template for sending link to the draft request form for the guest user.                                                                                                                 |                    |                       | GR-SMS1              | eFamilyHistory - Link to your Saved request                                                       | FH-SignatureBlock     |
      #| FH-EMAIL2                | Template for sending link to the applicant to download the unceritifed copies of certificates in PDF format                                                                             |                    |                       | GR-SMS1              | eFamilyHistor - Undertified certificates - PDF download link                                      | FH-SignatureBlock     |
      #| BRC-Email1               | Corro Template for Notifying that Birth Certificate Application has been received.                                                                                                      |                    |                       | GR-SMS1              | Birth Certificate Application - Received                                                          | BR-EmailSignature     |
      #| DRC-Email1               | Corro Template for Notifying that Death Application has been received.                                                                                                                  |                    |                       | GR-SMS1              | Death Certificate Application - Received                                                          | DR-SignatureBlock     |
      #| RRC-Email1               | Corro Template for Notifying that Relationship Application has been received.                                                                                                           |                    |                       | GR-SMS1              | Relationship Certificate Application - Received                                                   | RR-SignatureBlock     |
      #| CONC-Email1              | Corro Template for Notifying that Change of Name Certificate Application has been received.                                                                                             |                    |                       | GR-SMS1              | Death Certificate Application - Received                                                          | CON-EmailSignature    |
      #| RDC-Email1               | Corro Template for Notifying that Receognised Details Certificate Application has been received.                                                                                        |                    |                       | GR-SMS1              | Recognised Details Certificate Application - Received                                             | COS-EmailSignature    |
      #| MRC-Email1               | Corro Template for Notifying that Marriage Application has been received.                                                                                                               |                    |                       | GR-SMS1              | Marriage Certificate Application - Received.                                                      | MR-EmailSignature     |
      #| BRC-Email2               | Corro Template for sending copy of Birth Certificate to Passport Office email                                                                                                           |                    |                       |                      | Birth certificate copy attached                                                                   | BR-EmailSignature     |
      #| DRC-Email2               | Corro Template for sending copy of Death Certificate to Passport Office email                                                                                                           |                    |                       |                      | Death certificate copy attached                                                                   | DR-SignatureBlock     |
      #| RRC-Email2               | Corro Template for sending copy of Relationship Certificate to Passport Office email                                                                                                    |                    |                       |                      | Relationship certificate copy attached                                                            | RR-SignatureBlock     |
      #| CONC-Email2              | Corro Template for sending copy of Change of Name Certificate to Passport Office email                                                                                                  |                    |                       |                      | Change of Name certificate copy attached                                                          | CON-EmailSignature    |
      #| RDC-Email2               | Corro Template for sending copy of Recognised Details Certificate to Passport Office email                                                                                              |                    |                       |                      | Recongnised Details certificate copy attached                                                     | COS-EmailSignature    |
      #| MRC-Email2               | Corro Template for sending copy of Marriage Certificate to Passport Office email                                                                                                        |                    |                       |                      | Marriage certificate copy attached                                                                | MR-EmailSignature     |
      #| DR-Email4                | Template to notify that DR Ceritifcate is compete                                                                                                                                       |                    |                       | GR-SMS1              | Death certificate application - Completed                                                         | DR-SignatureBlock     |
      #| BR-Email7                | Corro Template to notify that BR Certificate is compete                                                                                                                                 |                    |                       | GR-SMS1              | Birth certificate application - Completed                                                         | BR-EmailSignature     |
      #| MR-Email10               | Template to notify that Marriage Ceritifcate is compete                                                                                                                                 |                    |                       | GR-SMS1              | Marriage certificate application - Completed                                                      | MR-EmailSignature     |
      #| COSC-Email1              | Corro Template for Notifying that COS Certificate Application has been received.                                                                                                        |                    |                       | GR-SMS1              | Email subject                                                                                     | COS-EmailSignature    |
      #| RRC-Email2               | Template to notify that Relationship Ceritifcate is compete                                                                                                                             |                    |                       | GR-SMS1              | Relationship certificate application - Completed                                                  | COS-EmailSignature    |
      #| CONC-Email2              | Template to notify that CON Ceritifcate is compete                                                                                                                                      |                    |                       | GR-SMS1              | Change of Name certificate application - Completed                                                | CON-EmailSignature    |
      #| RDC-Email2               | Template to notify that Recognised Details Ceritifcate is compete                                                                                                                       |                    |                       | GR-SMS1              | Recognised details certificate application - Completed                                            | COS-EmailSignature    |
      #| RDC-Email2               | Template to notify that COS Ceritifcate is compete                                                                                                                                      |                    |                       | GR-SMS1              | Change of Sex certificate application - Completed                                                 | COS-EmailSignature    |
      #| CertA-Email8             | Corro Template to list exceptions and notify that additional information is required to proceed with Certificate application assessment                                                 | Transaction        | Application           | GR-SMS1              | Certificate Application - Additional Information required                                         | CERTA-EmailSignature  |
