Feature: Creating Correspondence Templates Placeholders for Letters.

  Scenario Outline: Create Letter Placeholders
    Given I am on CORE Admin site
    When I want to create a "Letter corro" template
    And I want to make the title "<Template Name>" and the description "<Template Description>" and the "<LifeEvent>" and the "<Document Type>"
    And I want the letter to have the "<Branding Template>" and the Signature Block to be "<Watermark Templates>"
    And I make the boy text "<Letter Corro Body>"
    Then I can save the template placeholder

    Examples: 
      | Template Name                                                     | Template Description                                                                                                                                                                                                                                                                    | LifeEvent      | Document Type    | Branding Template      |
      #| Transaction Underpayment                                          | User selects Finish transaction and transction is underpaid.  CBDM user selected generate Letter.  Letter is automatically saved in  Application’s Related documents Underpayment”.  Correspondence is sent without user intervention. (IS CBDM core - used by internal BDM users only? |                |                  |                        |
      #| CON-Letter15                                                      | Corro letter template advising Declarant 1 to inform Declarant 2, they have not completed Part 2                                                                                                                                                                                        | Change of Name | CON Notification | CON-LetterBranding     |
      #| Letter - CON notify Adult Parole Board of completed CON           | Corro Template to notify the Adult Parole Board that a CON has been completed for an Offender                                                                                                                                                                                           | Change of Name | CON Notification | CON-LetterBranding.doc |
      #| Letter - CON notify Chief Commissioner of Police of completed CON | Corro Template to notify the Chief Commissioner of Police that a CON has been completed for a Registered Sex Offender                                                                                                                                                                   | Change of Name | CON Notification | CON-LetterBranding.doc |
      #| Letter - Financial defaullts/judgements found against applicant   | Corro Template where finacial defaults or judgements have been found. Applicant to provide written sign off / acknowledgement from creditors                                                                                                                                            | Change of Name | CON Notification | CON-LetterBranding.doc |
      #| Letter - CON not required and cancelled as Married in Australia   | Corro Template to notify that CON is NOT required as Marriage occurred in Australia. Application cancelled, documents and fee returned                                                                                                                                                  | Change of Name | CON Notification | CON-LetterBranding.doc |
      #| DR-Letter11                                                       | Template to advise MCCD signed by wrong doctor	Deaths	COD	DR-LetterBranding.doc                                                                                                                                                                                                         |                |                  |                        |
      #| DR-Letter12                                                       | Template to advise requirements for overseas death	Deaths	DRS	DR-LetterBranding.doc                                                                                                                                                                                                     |                |                  |                        |
