package modules;

import org.apache.commons.lang3.RandomStringUtils;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.PageFactory;

import helpers.Helper;
import pageobjects.CoreControls;
import pageobjects.CoreRNPage;

public class FillRNForm {

	public static String applicant1FamilyName = RandomStringUtils.randomAlphabetic(6);
	public static String applicant1GivenName = RandomStringUtils.randomAlphabetic(6);
	public static String applicant1FatherFirstName = RandomStringUtils.randomAlphabetic(6);
	public static String applicant1MotherFirstName = RandomStringUtils.randomAlphabetic(6);
	public static String applicant2FamilyName = RandomStringUtils.randomAlphabetic(6);
	public static String applicant2FirstName = RandomStringUtils.randomAlphabetic(6);
	public static String applicant2FatherFirstName = RandomStringUtils.randomAlphabetic(6);
	public static String applicant2MotherFirstName = RandomStringUtils.randomAlphabetic(6);

	public static void Execute(WebDriver driver) throws Throwable {
		PageFactory.initElements(driver, CoreRNPage.class);
		PageFactory.initElements(driver, CoreControls.class);
		Thread.sleep(3000);
		Helper.clickItem(CoreRNPage.additionalNotificationDetailsLink);
		Helper.inputItem(CoreRNPage.dateReceivedAtRegistry, "10/09/2017");
		CoreRNPage.dateReceivedAtRegistry.sendKeys(Keys.TAB);
		CoreRNPage.dateReceivedAtRegistry.sendKeys(Keys.TAB);
		Helper.inputItem(CoreRNPage.applicant1DateSubmittedDay, "01");
		Helper.inputItem(CoreRNPage.applicant1DateSubmittedMonth, "09");
		Helper.inputItem(CoreRNPage.applicant1DateSubmittedYear, "2017");
		Helper.inputItem(CoreRNPage.applicant2DateSubmittedDay, "01");
		Helper.inputItem(CoreRNPage.applicant2DateSubmittedMonth, "09");
		Helper.inputItem(CoreRNPage.applicant2DateSubmittedYear, "2017");
		Helper.inputItem(CoreRNPage.typeOfRelationship, "Domestic");
		Helper.inputItem(CoreRNPage.applicant1FamilyName, "Auto" + applicant1FamilyName);
		Helper.inputItem(CoreRNPage.applicant1FamilyNameAtBirth, "Auto" + applicant1FamilyName);
		Helper.inputItem(CoreRNPage.applicant1FirstName, "Auto" + applicant1GivenName);
		Helper.inputItem(CoreRNPage.applicant1Sex, "Male");
		Helper.inputItem(CoreRNPage.applicant1BirthDay, "01");
		Helper.inputItem(CoreRNPage.applicant1BirthMonth, "01");
		Helper.inputItem(CoreRNPage.applicant1BirthYear, "1990");
		Helper.inputItem(CoreRNPage.applicant1Occupation, "Bank Officer");
		Helper.inputItem(CoreRNPage.applicant1RelationshipStatus, "Married");
		Helper.inputItem(CoreRNPage.applicant1BirthSuburb, "Melbourne");
		Helper.inputItem(CoreRNPage.applicant1AddressLine1, "10 some street");
		Helper.inputItem(CoreRNPage.applicant1AddressSuburb, "Melbourne");
		Helper.inputItem(CoreRNPage.applicant1AddressPostcode, "3000");
		Helper.inputItem(CoreRNPage.applicant1ResidingInVictoria, "Yes");
		Helper.inputItem(CoreRNPage.applicant1Phone, "0454545450");
		Helper.inputItem(CoreRNPage.applicant1Parent1Type, "Mother");
		Helper.inputItem(CoreRNPage.applicant1Parent1FamilyName, "Auto" + applicant1FamilyName);
		Helper.inputItem(CoreRNPage.applicant1Parent1FamilyNameAtBirth, "Auto" + applicant1FamilyName);
		Helper.inputItem(CoreRNPage.applicant1Parent1FirstName, "Auto" + applicant1MotherFirstName);
		Helper.inputItem(CoreRNPage.applicant1Parent2Type, "Father");
		Helper.inputItem(CoreRNPage.applicant1Parent2FamilyName, "Auto" + applicant1FamilyName);
		Helper.inputItem(CoreRNPage.applicant1Parent2FamilyNameAtBirth, "Auto" + applicant1FamilyName);
		Helper.inputItem(CoreRNPage.applicant1Parent2FirstName, "Auto" + applicant1FatherFirstName);
		Helper.inputItem(CoreRNPage.applicant1DateOfRelationshipDay, "01");
		Helper.inputItem(CoreRNPage.applicant1DateOfRelationshipMonth, "01");
		Helper.inputItem(CoreRNPage.applicant1DateOfRelationshipYear, "2015");
		Helper.inputItem(CoreRNPage.applicant1RelCelebrationDay, "01");
		Helper.inputItem(CoreRNPage.applicant1RelCelebrationMonth, "01");
		Helper.inputItem(CoreRNPage.applicant1RelCelebrationYear, "2015");
		Helper.inputItem(CoreRNPage.applicant2ContactFamilyName, "Auto" + applicant2FamilyName);
		Helper.inputItem(CoreRNPage.applicant2ContactFirstName, "Auto" + applicant2FirstName);
		Helper.inputItem(CoreRNPage.applicant2ContactPhone, "0454545450");
		Helper.inputItem(CoreRNPage.applicant1HowPoiVerified, "DPOI");
		Helper.inputItem(CoreRNPage.applicant2FamilyName, "Auto" + applicant2FamilyName);
		Helper.inputItem(CoreRNPage.applicant2FamilyNameAtBirth, "Auto" + applicant2FamilyName);
		Helper.inputItem(CoreRNPage.applicant2FirstName, "Auto" + applicant2FirstName);
		Helper.inputItem(CoreRNPage.applicant2Sex, "Female");
		Helper.inputItem(CoreRNPage.applicant2BirthDay, "01");
		Helper.inputItem(CoreRNPage.applicant2BirthMonth, "01");
		Helper.inputItem(CoreRNPage.applicant2BirthYear, "1990");
		Helper.inputItem(CoreRNPage.applicant2Occupation, "Bank Officer");
		Helper.inputItem(CoreRNPage.applicant2RelationshipStatus, "Married");
		Helper.inputItem(CoreRNPage.applicant2BirthSuburb, "Melbourne");
		Helper.inputItem(CoreRNPage.applicant2AddressLine1, "10 some street");
		Helper.inputItem(CoreRNPage.applicant2AddressSuburb, "Melbourne");
		Helper.inputItem(CoreRNPage.applicant2AddressPostcode, "3000");
		Helper.inputItem(CoreRNPage.applicant2ResidingInVictoria, "Yes");
		Helper.inputItem(CoreRNPage.applicant2Phone, "0454545450");
		Helper.inputItem(CoreRNPage.applicant2Parent1Type, "Mother");
		Helper.inputItem(CoreRNPage.applicant2Parent1FamilyName, "Auto" + applicant2FamilyName);
		Helper.inputItem(CoreRNPage.applicant2Parent1FamilyNameAtBirth, "Auto" + applicant2FamilyName);
		Helper.inputItem(CoreRNPage.applicant2Parent1FirstName, "Auto" + applicant2MotherFirstName);
		Helper.inputItem(CoreRNPage.applicant2Parent2Type, "Father");
		Helper.inputItem(CoreRNPage.applicant2Parent2FamilyName, "Auto" + applicant2FamilyName);
		Helper.inputItem(CoreRNPage.applicant2Parent2FamilyNameAtBirth, "Auto" + applicant2FamilyName);
		Helper.inputItem(CoreRNPage.applicant2Parent2FirstName, "Auto" + applicant2FatherFirstName);
		Helper.inputItem(CoreRNPage.applicant2DateOfRelationshipDay, "01");
		Helper.inputItem(CoreRNPage.applicant2DateOfRelationshipMonth, "01");
		Helper.inputItem(CoreRNPage.applicant2DateOfRelationshipYear, "2015");
		Helper.inputItem(CoreRNPage.applicant2RelCelebrationDay, "01");
		Helper.inputItem(CoreRNPage.applicant2RelCelebrationMonth, "01");
		Helper.inputItem(CoreRNPage.applicant2RelCelebrationYear, "2015");
		Helper.inputItem(CoreRNPage.applicant2HowPoiVerified, "DPOI");
		CoreControls.validateForm();
		CoreControls.overrideExceptionsOnform();
//		CoreControls.actionList.sendKeys("Match to Application");
//		CoreControls.go.click();
//		Thread.sleep(3000);
//		CoreControls.firstRadioButtonMatch.click();
//		CoreControls.matchButton.click();
//		Thread.sleep(3000);
	}
}
